add link

diff --git a/tdp-config-catalog-cce/Jenkinsfile b/tdp-config-catalog-cce/Jenkinsfile
--- a/tdp-config-catalog-cce/Jenkinsfile
+++ b/tdp-config-catalog-cce/Jenkinsfile
@@ -310,6 +310,27 @@ pipeline {
                         --wait \
                         --timeout ${TIMEOUT_SECONDS}s
 
+
+                        echo ""
+                        echo "=========================================="
+                        echo "Iniciando Health Check público..."
+                        echo "ELB IP: ${env.elb_public_ip}"
+                        echo "=========================================="
+
+                        for i in \$(seq 1 20); do
+                        echo "Intento \$i..."
+                        if curl -sf http://${env.elb_public_ip}/index.html; then
+                            echo ""
+                            echo "Aplicación disponible y funcionando correctamente."
+                            exit 0
+                        fi
+                        sleep 10
+                        done
+
+                        echo ""
+                        echo "ERROR: Health check falló después de múltiples intentos."
+                        exit 1
+
                         '''
                     }
                 }
